### ISSUE TITLE
Not working in MacOS

### ISSUE THREAD

**Issue by stefaniecg** [Spiker985/x-terminal-reloaded#65] opened 2023-09-01 10:57 UTC
Can some one help, i cannot **x-terminal-reloaded 14.2.6** it working in **MacOS pulsar 1.108.0 arm64**. 
Nothing happens when i click to open a terminal.

**Comment by stefaniecg** [comment] 2023-09-01 20:50
I managed to find out what the problem is, see picture below:

![image](https://cvws.icloud-content.com/B/AcVCcQ2bSKPKzb-5yYctSMb9mtkfAcC_MuIqG7F3R09k73yXHzJB7wlB/error.png?o=AtvBD8NuBujv2bmQkEo2e67bV3_7ROP5h2uH-3J0JXsX&v=1&x=3&a=CAog3j9aFmWuHPjTgqErRxmPGoon0S8PrGeprlNpZ9BmBNESaxCOioqUpTEYjufllaUxIgEAUgT9mtkfWgRB7wlBaiVTk8PoR234P1o1TMwPlnKUTf8BSlnQ1yuss2qdGNRGfcqw7Y2OciV6IWnVeymJaP2Wlu6PknMUHvF3r0h-f5XITTE9VglxhThGKTRn&e=1693605000&fl=&r=a201682a-3b9f-4cd4-b6be-fca98c9824a3-1&k=dSsxYBZQCsjxRDmZzBWOtQ&ckc=com.apple.clouddocs&ckz=com.apple.CloudDocs&p=107&s=Y-ETlCcfwJtgqOVa6RDU72vOKJY&cd=i)

**Comment by confused-Techie** [comment] 2023-09-01 21:18
@stefaniecg What might be able to fix the issue for you, is running something like:

```bash
cd ~/.pulsar/packages/z-terminal-reloaded
npx electron-rebuild -v 12.2.3
```

This will rebuild the package to that specific version of Electron. Pulsar should be able to do this automatically, but it's a worth a try to see if it can fix your issue.

(Keep in mind to run this you must have NodeJS installed)

**Comment by stefaniecg** [comment] 2023-09-01 21:25
after running it on command line: 
`zsh: command not found: npx`

**Comment by confused-Techie** [comment] 2023-09-01 23:19
@stefaniecg Do you have NodeJS installed?

Like I said, you need to have NodeJS installed (which should also install NPM and NPX), since like you can tell, your shell can't find the `npx` command.

**Comment by stefaniecg** [comment] 2023-09-02 08:42
Is there any other way, other than instaling NodeJS? 
If possible i'd like to avoid installing stuff i won't use in the long run. 
Isn't there a way to fix it trough pulsar?

I remember i installed this termial in my linux-ubuntu comptuer, and as far as i can remember, there it worked.
So it has to be a pulsar/macos problem, isn't it?

**Comment by confused-Techie** [comment] 2023-09-02 23:57
This is something we are hoping to try and fix on Pulsar's end, you can see when we first discovered this was something that we needed to address [here](https://github.com/pulsar-edit/pulsar/issues/359).

But while efforts have been made to totally resolve this, as you are seeing it is still an issue.

But I think the reason you originally saw this working, was because of two things:

1. This issue doesn't always seem to happen. It's not readily reproduceable
2. The native modules this package depends on have been upgraded, and if memory serves the most recent upgrades have lost support of prebuilt native modules, meaning these built modules are no longer provided by the dependency, which now means every installation must built them itself.

So what this means, is while the above should 100% resolve your issue, if you're unwilling to install NodeJS, you could either wait for this to happen automatically within Pulsar, or really you could likely attempt to uninstall the package, and try installing again. Since like I said, it's an intermittent issue, a second installation attempt may work properly, it may not. So reinstalling could be attempted to resolve the issue, but there is 0 guarantee that it will fix it.

Otherwise, you can keep an eye on the issue I linked, to see any updates made there

**Comment by karmnik** [comment] 2023-10-26 06:32
pulsar 1.110.0
x-terminal-reloaded 14.3.0

node-pty-prebuilt-multiarch@0.10.0 – dlopen(/Users/user/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node, 0x0001): tried: '/Users/user/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/user/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node' (no such file), '/Users/user/.pulsar/packages/x-terminal-reloaded/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by Spiker985** [comment] 2023-10-30 16:14
Unfortunately, this is duplicate of #27

**Closed by Spiker985** 2023-10-30 16:14 UTC
